### ISSUE TITLE
Cannot see the Text, only the link show.

### ISSUE THREAD

**Issue by klemensms** [MscrmTools/PCF-Controls#10]
Please see screenshots, I "am sure" I have configured it correctly, the link shows and works, however, the actual message does not. I have changed things around - without any success. 

![2020_05_29_18_20_59_0064](https://user-images.githubusercontent.com/38175124/83287215-2f31f600-a1d9-11ea-995a-30e97080f1d8.jpg)
![2020_05_29_18_20_57_0063](https://user-images.githubusercontent.com/38175124/83287217-2fca8c80-a1d9-11ea-8096-7ef209b2123f.jpg)

**Comment by sabharwalvarun** [comment]
Hi! I am also facing the same issue, was it resolved?

**Comment by klemensms** [comment]
unfortunately, I haven't hear d back yet.

**Comment by MscrmTools** [comment]
Sorry, I did not see the notifications from github... Let me check

**Comment by MscrmTools** [comment]
Can you check with latest release (1.8)?

**Comment by klemensms** [comment]
@MscrmTools thank you very much, that bug has now been resolved, both text and link are displaying as expected. 

Another thing I noticed about the link: there is no way to select the link

**Comment by klemensms** [comment]
@sabharwalvarun this is now resolved!

**Comment by MscrmTools** [comment]
Is it resolved or not? You posted two different comments

**Comment by klemensms** [comment]
@MscrmTools apologies, the issue is resolved :-) 

![image](https://user-images.githubusercontent.com/38175124/93660242-930c5300-fa44-11ea-8aa5-99992d570858.png)

**Comment by MscrmTools** [comment]
Gréât!
