### ISSUE TITLE
Action Button - You have exceeded the maximum number of 4000 characters in this field.

### ISSUE THREAD

**Issue by brettofthewild** [MscrmTools/PCF-Controls#112]
I'm sure this is user error, but what am I doing wrong here? What settings need to be set on my Model-Driven App Form for the Action Button to work correctly? 

I currently have the Action Button component set on a field aptly named "Button" that has a 4,000 character limit. Each time I click the button, this is the error I get:
![image](https://user-images.githubusercontent.com/79302547/203431237-40c25cea-b6e6-44ea-b7a1-fb2bf517bcfb.png)

Here's my settings. Everything else is default:
![image](https://user-images.githubusercontent.com/79302547/203431632-dd39168b-fc72-408d-9768-bc73a3c64f20.png)

Let me know! Thanks!

**Comment by brettofthewild** [comment]
Hey there. Anyone seeing this?

**Comment by MscrmTools** [comment]
This error should not happen. The button sends the ID or the Label of the button to the bound attribute.
Unless the script associated with the button is wrong, I cannot see where the issue comes from

**Comment by brettofthewild** [comment]
This occurs when literally no script is associated with the button whatsoever. If the button is simply published to a form, the error occurs. I deleted the managed solution and re-added it to see if there would be any difference, but sadly there was not.

I replaced a Date field instead, and that’s working just fine. Honestly not sure what the issue is with the button and text fields.

**Comment by alanrroberts** [comment]
> Hey there. Anyone seeing this?

Yep seeing the same here.  Can't get it to work with a text field but fine with a date.

**Comment by MscrmTools** [comment]
@alanrroberts if you can test this one too with the version I posted on the other issue, that would be nice

**Comment by alanrroberts** [comment]
@MscrmTools working as expected now.  Thanks for tweaking that so quickly!
