### ISSUE TITLE
Feature Request: Element IDs

### ISSUE THREAD

**Issue by alanrroberts** [MscrmTools/PCF-Controls#125]
Hi, would it be feasible to add an id field to each control that was then used as the HTML element id?  This would allow us to specify a value that we could reliably use with document.getElementById etc e.g. to enable and disable buttons at various times.

Thanks

Alan

**Comment by MscrmTools** [comment]
@alanrroberts Not sure why you need this. Enabling or disabling the control using standard SDK methods does the trick (see gif below). Or there are other scenario not covered?

Here is a simple code :
```
var ctrl = form.getControl("demo_actionbutton");
if(!ctrl) return;

Xrm.Navigation.openAlertDialog({text:"tic"}).then(
                function(){
                       let state = ctrl.getDisabled();
                       ctrl.setDisabled(!state);
});
```

that produces this behavior (the alert dialog is outside the recorded screen area, but still)
![ab](https://user-images.githubusercontent.com/10774317/207606761-2005b3c4-15f6-4ed8-ae37-d8e60940e96c.gif)

**Comment by alanrroberts** [comment]
Thanks @MscrmTools.  I may be trying to do the impossible but I am employing the button on a locked form (i.e. the record is set to inactive) in order to be able to change a field using javascript.  The requirement is to have a record filled in by one team and then locked to prevent changes.  Another team, the validation team, should be able to mark the record as validated.  The idea was to place a button on the form to allow them to do this.  So far this all works as expected.  All I was wanting to do now was to have the button disabled when the record status isn't set to "validation" i.e. so it only works at that time.  So this would be trying to disable the button independently from the state of the control it is bound to.  I've done a bit of playing though and it doesn't seem to be as simple as just marking the button as disabled in the HTML so you can probably reject the request.

**Comment by MscrmTools** [comment]
As it is a very specific feature request, I think it won't be implemented
