### ISSUE TITLE
Feature Request: Select All with Grouping

### ISSUE THREAD

**Issue by bpremji** [MscrmTools/PCF-Controls#126]
Hi @MscrmTools,

Great set of tools :)

Not sure if this a bug or a feature request for the NN Checkboxes

When adding Grouping and then applying a filter to the data set, the select all button adds all records in the Group, not only the ones selected in the search.

In the following example, I group the records by the first letter of the surname, if I apply a filter for the letter q in the search, the following appears

![Screen](https://user-images.githubusercontent.com/45225250/208014877-207d3119-9f0b-436f-8e3f-7bc50e2223b2.png)

If I select all on the 'B' group, I would like only the 3 records in the screenshot to be added to the NN relationship, however all the records that are in the B group are added.

Thanks

**Comment by MscrmTools** [comment]
Hi,
This is a mix of bug/feature request but your point is definitively valid!
I will make sure only visible items are used

**Comment by MscrmTools** [comment]
@bpremji I released a new version that fixes this behavior
