### ISSUE TITLE
Lookup To Dropdown - Not showing as component option

### ISSUE THREAD

**Issue by connorI55** [MscrmTools/PCF-Controls#138]
I have the solution installed and published. I'm not seeing this control as an option for any lookup fields on my form. What am I missing?

**Comment by MscrmTools** [comment]
It does show on my environment, wether it's on classic or modern form designer

![image](https://user-images.githubusercontent.com/10774317/219390267-c83977aa-f823-48a3-a524-239f9c5b5bcb.png)

**Comment by connorI55** [comment]
Maybe this will help?
https://powerusers.microsoft.com/t5/Power-Apps-Pro-Dev-ISV/PCF-control-not-visible-from-quot-Add-control-quot-wizard/m-p/951051#M4505

Do you have any troubleshooting steps I could follow? Saying it works for you doesn't exactly help :/
