### ISSUE TITLE
Suggestion: Default the "Switch off color" to #dddbdb for toggle control

### ISSUE THREAD

**Issue by acraigx** [MscrmTools/PCF-Controls#14]
For the switch off color when using a toggle control, I found it confusing when there was nothing chosen since the default color is white and therefore the control down't show a toggle until you click on it.

**Comment by MscrmTools** [comment]
@acraigx Not sure to understand what PCF control you are talking about.

I tested both Custom Switch and NN Checkboxes with no off color and I did not reproduced. 

Can you send me screenshot of the configuration and the rendering in the form?
