### ISSUE TITLE
How to implement the NN Checkboxes

### ISSUE THREAD

**Issue by falstaffjobs** [MscrmTools/PCF-Controls#140]
Hi,

not really an issue, but rather a question: how do I setup the n:n checkboxes in power apps customizing? I have managed to import the solution to the enviroment, but don't know which field I need to insert and adapt in order to get the NN Checkboxes on my forms.

Thanks in advance
Georg

**Comment by MscrmTools** [comment]
Hi @falstaffjobs, this control must be applied to a subgrid which displays a NN relationship. It is not a field PCF.

**Comment by falstaffjobs** [comment]
I've tried to apply it on the subgrid with add control - but can't find a NN Checkbox option in the list. I have imported the managed solution. What would be the name of the control?

**Comment by MscrmTools** [comment]
It should be `Checkbox list`

**Comment by falstaffjobs** [comment]
ok I found it - thank you so much for your help! I've set the control, but I get the following error in the frontend:

Error Details: Cannot read properties of undefined (reading 'getAll')
Activity Id: d79b4061-addc-4d0a-a864-d73628d940c3

any idea what's missing?

**Comment by MscrmTools** [comment]
The only code that uses a `getAll` method is when reading ManyToManyRelationships of the current entity. Are you sure you are using a subgrid with a NN relationship?

**Comment by falstaffjobs** [comment]
oh gosh - my bad, I've been on the wrong relationship. all good, thanks!
