### ISSUE TITLE
ActionButton_Display_Key - not triggered click

### ISSUE THREAD

**Issue by radeknovak** [MscrmTools/PCF-Controls#148]
Hi! 
I have a problem.
I configured ActionButton_Display_Key component to text field.
It is visible and I can click it. OnChange event is configured. 
But when I click no OnChange function is running.

**Comment by EnterPro777** [comment]
I have the same issue. My Script ist simple and I also track it with console.logs. But when I click on button, nothing happens. The script doesnt start onChange

**Comment by joannachongshen** [comment]
I had the same issue. After some trial and errors, I realized the text property must not be null for the button to work. So if you bound it to a field and that field is null, the action button will not work.
