### ISSUE TITLE
NNCheckboxes show preselected checkboxes when creating the record and don't load the data after saving/refresh

### ISSUE THREAD

**Issue by scherle** [MscrmTools/PCF-Controls#157]
Hi team, 

I'm trying to use the NNCheckboxes for a many-to-many relationship and it actually works:
- when I untick and tick again a checkbox, the sub grid adds the relation
- when I untick it again, the relation is removed from the sub grid

But: 
- when I reload the page all checkboxes are ticked by default no matter which relation is existing or not
- when creating the whole new record all checkboxes are ticked by default, but without adding relations

So overall, it just doesn't load the correct state of each checkbox. 

It would be great if you could take a look.

Thanks,
Steffen

PS: this is how it looks after refreshing:
![image](https://github.com/MscrmTools/PCF-Controls/assets/6567932/8b28ecb6-38c9-44de-8185-7f1084cc1459)

**Comment by scherle** [comment]
Just to mention:
I'm using the latest release [v1.12.3.0](https://github.com/MscrmTools/PCF-Controls/releases/tag/v1.12.3.0) as a managed solution.

**Comment by MscrmTools** [comment]
I think I saw this behavior when the subgrid was added without ticking the checkbox "display related records" so it actually shows all records which renders as all records ticked in the PCF.
Check if you added the subgrid correctly

**Comment by scherle** [comment]
Oh yes, this was causing it and it works now. Thank you very much! 
If you could add this as a note to the readme it would be great. 

Another question about the Filter Attribute:
what does it do or how does it work?

My goal is to filter the options down to the same related record (in my case: "Related Lead" which is related to "PV Arrays" and the table which is shown in the form "Offers"):
![image](https://github.com/MscrmTools/PCF-Controls/assets/6567932/bb911e05-47aa-47c3-bba2-142e3944c7bb)

When I select "Related Lead" as the table column, it shows the wrong options. 
Do you have an idea how I can achieve this?

**Comment by scherle** [comment]
This screenshot will help to explain it a bit:
![image](https://github.com/MscrmTools/PCF-Controls/assets/6567932/3387e88b-53d7-44d0-869e-6fa84a7ad41b)

**Comment by scherle** [comment]
So following [this tutorial](https://carldesouza.com/filtering-subgrids-in-dynamics-365-power-apps-with-setfilterxml/) I know how to set the right filter via JS, but I don't know how I can refresh the Checkbox List control.

Can you give me a hint?

**Comment by MscrmTools** [comment]
As mentioned in the documentation, even if you can select a filter of type Lookup, there seems a bug still exists that prevents the filter feature to works correctly.
I added this type of filter hoping the bug would be fixed but it seems it's not yet

**Comment by scherle** [comment]
Ok, thank you. 
But is possible to refresh the NNCheckboxes control via JavaScript somehow?

**Comment by MscrmTools** [comment]
Note that I'm aware of
