### ISSUE TITLE
Action Button: Dynamically change color through Javascript

### ISSUE THREAD

**Issue by gavinpollockacora** [MscrmTools/PCF-Controls#166]
Hi - is it possible to access to Color property dynamically rather than through another column or such? I wanted to use the button and for simplicity (as I already have other JS running) dynamically update the color of the button at certain other events in the JS on the form. Is that possible in some way?

Cheers!
Gavin

**Comment by MscrmTools** [comment]
It's only possible if using another text column that you will fill the HTML color you are expecting.
