### ISSUE TITLE
Action Button only trigger once

### ISSUE THREAD

**Issue by puneet16** [MscrmTools/PCF-Controls#167]
I added action contriol on my custom text field. It only triggered when I clicked first time but after that the onchange event is not firing.
Could be please help me to find the problem? 

I want to trigger onchange function whenever user click on the button.

**Comment by gavinpollockacora** [comment]
Hi, check the example on the home page. You need to clear the value every time in the onchange function otherwise the text value is not 'changing' so it won't trigger. Add this into your onchange event:

let attribute = executionContext.getEventSource();
    
    attribute.setValue(null);
    attribute.setSubmitMode("never");

**Comment by MscrmTools** [comment]
Thanks for helping @gavinpollockacora
