### ISSUE TITLE
[Question] Dynamically adjust Action button width to fit size of section in Model-driven app

### ISSUE THREAD

**Issue by Ruben-e-d** [MscrmTools/PCF-Controls#168]
Hi,

I am new to PCF and Fluent-UI but I came across your Action button and started playing with it.
I love the capabilities PCF has and how you've made the Action button, but I was wondering if there is a way to automatically adjust the width of the button based on the size of the section it is located in.

Unfortunately, I can't find anything about this anywhere else, so I figured I'll just contact the developer of the button.
I have tried values as:

- stretch
- fit-content

As per [CSS documentation](https://developer.mozilla.org/en-US/docs/Web/CSS/width#browser_compatibility).
But that probably only looks at the content of the button itself not at the section where the button is located in this case:
![image](https://github.com/MscrmTools/PCF-Controls/assets/170458295/ab56921e-760e-4fbe-a5a9-d24d518026b3)

Desired result:
![image](https://github.com/MscrmTools/PCF-Controls/assets/170458295/cc40a4db-c02f-4201-b316-a2fa94fbfe38)

Desired result when section size changes:
![image](https://github.com/MscrmTools/PCF-Controls/assets/170458295/7f783ca8-b456-45fb-b66b-9f4e53889856)

![Schermafbeelding 2024-05-30 134716](https://github.com/MscrmTools/PCF-Controls/assets/170458295/e077d5e6-d784-432d-979e-f2991831bdd5)

The size of sections in Model-driven apps also dynamically adjust to the size of the screen, the zoom of the browser, aspect ratio and such. I was wondering if this is also possible with PCF in combination with React/Fluent UI.

I'd love to hear your thoughts on this.
Thanks in advance.

**Comment by MscrmTools** [comment]
unfortunately, PCF are not aware of the context/UI they are added in.
And playing with DOM is not supported so I'm not sure what you want is achievable

**Comment by Ruben-e-d** [comment]
Hi,

Thank you for your quick response.
Since what I asked for is not possible, I was wondering if it is possible to manipulate PCF controls, like width in the example above, with form scripts? If that is the case I can achieve this by putting a JScript function on the on load of a form and change it that way. It will be the right size once the form loads for every user.

Thank you.

**Comment by MscrmTools** [comment]
I guess it should be possible but not supported.
Browsing the DOM of the form should let you find some selectors to find the button and resize it dynamically

**Comment by Ruben-e-d** [comment]
In that case I'll look into that. Thanks for the answers.
Have a good one.

**Comment by Ruben-e-d** [comment]
Sorry to bother you again, but I have been playing around with the button today and may have found something.
While looking around I have found a function in PCF called `context.mode.trackContainerResize(Boolean)` [that allows the dimensions of the container to be read through][(url](https://learn.microsoft.com/en-us/power-apps/developer/component-framework/reference/mode/trackcontainerresize)) `context.mode.allocatedWidth` and `context.mode.allocatedHeight` and also kicks off the `UpdateView` if any of these dimensions change.

I have added the this into the configuration of the button but for some reason the width does not get updated even though it puts a pixel value into the width of the props.

Do you have any idea what I'm doing wrong?
I have added the following parts to the code:

- index.ts
- Inside the `public init`:
- `context.mode.trackContainerResize(context.parameters.trackContainerResizeValue.raw === "1" ? true : false);`
- Inside the `private renderControl`:
- `width: context.parameters.trackContainerResizeValue.raw === "1" ? `${context.mode.allocatedWidth}px` : context.parameters.trackContainerResizeValue.raw === "0" && context.parameters.width.raw !== null ? context.parameters.width.raw : "auto"`

- ControlManifest.Input.xml
- `<property 
      name="trackContainerResizeValue" 
      display-name-key="trackContainerResizeValue_Display_Key" 
      description-key="trackContainerResizeValue_Desc_Key" 
      of-type="Enum" 
      default-value="0" 
      usage="input" 
      required="true">
      <value name="true" display-name-key="yes_Resize_Display_Key" description-key="yes_Resize_Desc_Key">1</value>
      <value name="false" display-name-key="no_Resize_Display_Key" description-key="no_Resize_Desc_Key">0</value>
    </property>`

I did not change anything in the .tsx as there was no need to, if I'm not mistaken.
The following happens when changing the width of the component container in npm start watch:

- Run through index.ts

1. trackContainerResizeValue = true  
![image](https://github.com/MscrmTools/PCF-Controls/assets/170458295/71b07dd6-2428-4b74-8f5f-5c0b7bac195f)
2. width: 600px, sometimes it reads -1px but after a second run of `renderControl(context)` it does return a valid pixel value.
![image](https://github.com/MscrmTools/PCF-Controls/assets/170458295/ff28df40-b9b9-4c71-9d41-4ac3d48dcb2d)
3. Width of button does not change:
![image](https://github.com/MscrmTools/PCF-Controls/assets/170458295/8ddf6553-3945-4a89-817c-0fd2aa919629)

If you are willing to help me out that would be great, if you need my files, let me know but they are basically the same as yours with the lines above added to it.
