### ISSUE TITLE
Action Button is not honoring the Disabled state

### ISSUE THREAD

**Issue by MitchMilam** [MscrmTools/PCF-Controls#22]
If you disable the underlying text control, the Action Button does not disable itself as well.

**Comment by MscrmTools** [comment]
Thnak you @MitchMilam, I will check it

**Comment by MscrmTools** [comment]
Should be good on latest version

**Comment by mverbanck** [comment]
> Should be good on latest version

Just tried it out, if the button is enabled it still seems clickable.

![image](https://user-images.githubusercontent.com/11208075/163198660-bdd1fd4c-8efe-44bc-94c4-fc8b0c68fbcf.png)

**Comment by MscrmTools** [comment]
But it should honor it if you configure it (sorry the capture is in French). Also, see  [configuration documentation](https://github.com/MscrmTools/PCF-Controls/blob/master/README.md#configuration-4)

![image](https://user-images.githubusercontent.com/10774317/163246087-d42c230d-f127-4695-96dc-c20bd360620a.png)

**Comment by mverbanck** [comment]
> But it should honor it if you configure it (sorry the capture is in French). Also, see [configuration documentation](https://github.com/MscrmTools/PCF-Controls/blob/master/README.md#configuration-4)
> 
> ![image](https://user-images.githubusercontent.com/10774317/163246087-d42c230d-f127-4695-96dc-c20bd360620a.png)

Thanks looked a little bit unlogic for me that this was in a configuration, but seemd indeed to work in that case.!

**Comment by MscrmTools** [comment]
The point is : sometimes, you would want to have a button that is always active, even if the form is disabled.
