### ISSUE TITLE
Simple Notification - Icons are missing

### ISSUE THREAD

**Issue by stuax** [MscrmTools/PCF-Controls#23]
With the simple notification, the icon at the start of the notification does not show (Text shows fine though).

![image](https://user-images.githubusercontent.com/13952745/90884796-4fbcb700-e3a8-11ea-8fae-270182921889.png)

**Comment by MscrmTools** [comment]
Yeah... I noticed that... but it seems more an issue/conflict between Model Driven Apps styles and React framework than a real bug in my control. 
I will try to investigate

**Comment by MscrmTools** [comment]
Well, it did work for me when I just tested... 
![image](https://user-images.githubusercontent.com/10774317/94037596-d01a7180-fdc5-11ea-92ae-4b89e267b2bd.png)

**Comment by MscrmTools** [comment]
@stuax does it still happen to you?
