### ISSUE TITLE
Action Button for Date Time

### ISSUE THREAD

**Issue by victorsolaya** [MscrmTools/PCF-Controls#24]
Hi,

Probably a good option to add the action button to trigger when onchange of a datetime since you know when that action has been triggered.

**Comment by MscrmTools** [comment]
Are you suggesting something like an "auto click" on the button when a datetime change?

**Comment by victorsolaya** [comment]
Sorry for the short description there.
What I would be suggesting is, to allow to set this button above a DateTime field, so everytime you click that button, it will set todays date or whatever the onchange code is in that DateTime field. Does that makes sense?

**Comment by MscrmTools** [comment]
So I guess this is exactly what the Action button currently does. When you click on it, it executes the onchange code of the attribute the button is bound to. 
So in this onchange event, you can put todays date in a date field.

The Action button is aimed to be very generic so that only the onchange event code performs action on the button click

**Comment by victorsolaya** [comment]
I mean, to "upgrade" this control so you can use this control in a DateTime field as well, not only SingleLine.Text. 
Instead this line  in your Manifest: 

`    <property name="BoundAttribute" display-name-key="BoundAttribute_Display_Key" description-key="BoundAttribute_Desc_Key" of-type="**SingleLine.Text**" usage="bound" required="true" />
`

I would go with something like group-type:
https://docs.microsoft.com/en-us/powerapps/developer/component-framework/manifest-schema-reference/type-group

So you can use this control in SingleLine, DateTimes...etc

**Comment by MscrmTools** [comment]
ah ok! got it!
I will add more attribute type for this control

**Comment by victorsolaya** [comment]
Thank you! Sorry for not being clear from the very first momento, I didn't know how to explain myself!
Many thanks for all your work!

**Comment by MscrmTools** [comment]
Done
