### ISSUE TITLE
Simple Notification: make link "clickable" / open link in new tab

### ISSUE THREAD

**Issue by klemensms** [MscrmTools/PCF-Controls#28]
What I noticed about the link:

it is not clickable (e.g. the linked page does not open)

it is not possible to select just the link, users need to start the selection with some text and remove that when pasting it into a new tab

![image](https://user-images.githubusercontent.com/38175124/93660273-e8486480-fa44-11ea-89a4-46a9de3f2a5c.png)

--> this means we removed all links, as they are not useful this way (techy people don't mind, but most users find this too complicated. Is there anything that can be done about this?

**Comment by MscrmTools** [comment]
It does work. 
I guess you just filled the property for the link text, but not the actual link (see capture below, both properties must be filled)

![image](https://user-images.githubusercontent.com/10774317/94024695-02bd6d80-fdb8-11ea-9512-e8c6a7537fbe.png)

**Comment by klemensms** [comment]
![image](https://user-images.githubusercontent.com/38175124/94025664-aacf3880-fdb0-11ea-8b0c-c29ae6e6ba96.png)

I missed the scroll bar - all working as it should, thanks for the quick feedback!

![image](https://user-images.githubusercontent.com/38175124/94025719-bae71800-fdb0-11ea-86b3-9588ce08b664.png)
