### ISSUE TITLE
Add search function to NN checkboxes

### ISSUE THREAD

**Issue by yruss** [MscrmTools/PCF-Controls#29]
Sometimes there're many records in the N:N relationship, so it would be nice if we can add a search bar to the N:N checkboxes, similar to the search bar available in out-of-the-box sub-grids.

**Comment by Niels-SL** [comment]
Yes, it would be great to be able to search. 

The [enhanced experience of adding products (preview)](https://docs.microsoft.com/en-us/dynamics365/sales-enterprise/add-products-enhanced-experience), that Microsoft is working on also looks very promising on that front.

Here you can search, filter and also see recently used products - all great features enhancing the user experience.
![enhanced experience](https://docs.microsoft.com/en-us/dynamics365/sales-enterprise/media/search-for-products.png)

**Comment by MscrmTools** [comment]
Better later than never!
@Niels-SL @yruss does it answer the need?
https://www.screencast.com/t/EJY6VwVv

**Comment by Niels-SL** [comment]
Yes! At least from my side. 

I am looking forward for the release 😊

**Comment by MscrmTools** [comment]
Available in latest release
