### ISSUE TITLE
Styling options Action Buttons (enhancement)

### ISSUE THREAD

**Issue by D365NL** [MscrmTools/PCF-Controls#31]
Hey, 

Thank you for making these PCF Controls! The action buttons help a lot. We are now using it to do custom qualify/disqualify/won/close commands without having to mess around with the ribbonworkbench. However, it would be really cool if we could make this 'production ready' by adding some ux/ui enhancements. 

The most important thing would be to be able to change the color of the button control and perhaps set a min/max width/height. Some final finishing touches would be to perhaps add icon support and allow the buttons to have some allignment options (center). 

These are just some enhancements. We don't have any trouble with the action button control except for the disabled state, but somebody else already openend a bug report for that.
![qualifydisqualify](https://user-images.githubusercontent.com/74908459/99958437-ab248980-2d89-11eb-9b0e-c56dd96206e6.JPG)
 ;)

**Comment by MscrmTools** [comment]
@D365NL it's a long time but I will finally push a new release with support for custom colors !

**Comment by MscrmTools** [comment]
colors are there!

**Comment by MscrmTools** [comment]
Icons are arriving too

**Comment by mverbanck** [comment]
> colors are there!

Could be me, but color of the button could be changed, as wel as the color on hover.
But the moment you click the button the color keeps holding the default color '#005a9e'

**Comment by MscrmTools** [comment]
You are correct, I did not add the possibility to set the color when button is in clicked state. 
I will

**Comment by MscrmTools** [comment]
Available in latest release
