### ISSUE TITLE
Select All Records Option?

### ISSUE THREAD

**Issue by dapicella** [MscrmTools/PCF-Controls#32]
Does this control have the ability to select all as an option instead of choosing each record?

**Comment by MscrmTools** [comment]
@dapicella Are you talking about the NN Checkboxes control?

**Comment by Niels-SL** [comment]
It would definitely be a great feature to be able to select all records within a group with a single click. Something similar to the functionality in the [Tree relationship](https://pcf.gallery/tree-relationships/) by Alex Shlega.

**Comment by MscrmTools** [comment]
@dapicella @Niels-SL does it answer the need?

![NNCheckboxesWithCategories](https://user-images.githubusercontent.com/10774317/105050072-ac162680-5a6d-11eb-865c-9828e16ab0d6.gif)

**Comment by Niels-SL** [comment]
@MscrmTools, yes that is great! That will definitely improve the user experience if the users have to select all/most records within a group. 

I think the word **all** should be included to avoid any confusion. If possible, it could also just be one button/text link instead of two like the example below:

![image](https://user-images.githubusercontent.com/46558783/105145276-cf3ce680-5afe-11eb-8c68-03f11f7df50e.png)

**Comment by MscrmTools** [comment]
The difficulty with one control is how to handle the value when only some records are checked...

**Comment by Niels-SL** [comment]
I see. It's also down in the very small details 🔎🙂

If it is one or two buttons doesn't really change that much. But having the option to select/unselect all records within a group is definitely a great improvement from a user experience perspective.

**Comment by MscrmTools** [comment]
Like this? 
![image](https://user-images.githubusercontent.com/10774317/105179666-e2b17700-5b29-11eb-923d-edd138136ba0.png)

**Comment by Niels-SL** [comment]
Yes, that is great

**Comment by MscrmTools** [comment]
ok, go for release :)

**Comment by MscrmTools** [comment]
released!

**Comment by Niels-SL** [comment]
That was fast! I just added a comment a few days ago, and now the control is updated with a great new feature. 

I just tested it, and it works like a charm. It's great to see that you have added the option to enable/disable the feature as well.

Great job!
