### ISSUE TITLE
Cannot install newer/latest managed solution

### ISSUE THREAD

**Issue by reanmouton** [MscrmTools/PCF-Controls#34]
Hi there
I have version 1.8 installed and wanted to update it with the latest solution. 
However, I get the following error:
![image](https://user-images.githubusercontent.com/22331932/106681719-ebc03f00-6625-11eb-9784-72229d42c767.png)

Can you please advise what's the best way to get around this? I understand that you can't change the Publisher name of a managed solution.

Thanks
Rean

**Comment by MscrmTools** [comment]
@reanmouton Sorry, I totally missed your message.
There was a change the way the solution is built so the publisher changed.
You need to uninstall the previous version of the solution ebfore installing the update.
Sorry for that
