### ISSUE TITLE
Adding control multiple times on the same form

### ISSUE THREAD

**Issue by bpremji** [MscrmTools/PCF-Controls#4]
Hi guys,

Firstly, great PCF :)

Think I have found an issue, here is my scenario:

I have 2 N:N relationships between the same 2 entities.  I have added the PCF control to the form on 2 different subgrids, each one representing a different relationship. I also have 2 different views on the subgrids showing the relevant data.  I set the Relationship name field in the input parameters of the PCF.

I tick 2 tickboxes on the first PCF and the records are added for that relationship.  I then in the second PCF tick 3 different records and the records are added correctly to that relationship (I checked the record counts using the Record Count plugin in XRMToolBox).  When I reload the form the first PCF has 5 of the tickboxes ticked and none are ticked in the second PCF.

Is the tool not designed to be present on the same form multiple times or have I configured it incorrectly?

Regards

**Comment by MscrmTools** [comment]
That must be an issue with the code.
I must admit I never tried to load the control twice for multiple NN relationships.
I will do

**Comment by MscrmTools** [comment]
Ok, so I reproduced the error and I guess it's more a product issue (PCF) than a code issue.
I will report to Microsoft and see what they have to tell me

**Comment by MscrmTools** [comment]
It was finally not an issue with PCF SDK.
Latest version fix this issue and allows to put multiple instances of the PCF control

![image](https://user-images.githubusercontent.com/10774317/69451672-3aa2f100-0d60-11ea-886d-e33b9a20cbde.png)

**Comment by mpolutta** [comment]
This helped me solve a similar issue. Looked at the source code changes to see what was done. Added an additional id distinguisher. So having multiple HTML elements on a CRM form with the same ID causes major confusion. Don't do that! Fix was line 244: https://github.com/MscrmTools/PCF-Controls/commit/025f5274942cdd84c1a29d01c4559efdd1a278ae#diff-9054d54164b880ef0ab5f5ab8759bc01529ac1226b23f8deab7b444227beaa49
