### ISSUE TITLE
Unable to change off/on toggle colors

### ISSUE THREAD

**Issue by lbphan406** [MscrmTools/PCF-Controls#5]
This is such an awesome control, thanks so much for sharing it! I am having a rather basic issue with changing the color of the toggle when the selection is off. I'm trying to turn it white (#FFFFFF) however, after setting this in the 'Switch Off color' parameter and publishing the form, it doesn't seem to do anything. 

I've tried different browsers with no luck. Any ideas?

**Comment by MscrmTools** [comment]
Not sure why it does not work for you but it does for me. Of course, as you specify white color, you cannot see the control anymore. But when clicking on it, the "On" color is displayed and the control is visible. See the gif below

Please be sure you are using the latest version

![2019-11-21_07-39-27](https://user-images.githubusercontent.com/10774317/69313548-24971280-0c32-11ea-9bc3-123b4ec27cfc.gif)
