### ISSUE TITLE
NNCheckbox selection only shows on Save event

### ISSUE THREAD

**Issue by Nahassa** [MscrmTools/PCF-Controls#58]
In my development environment, I've started seeing an error with the NNCheckbox PCF control, where the selection is not rendered for associated records until a Save event is run.

Has anyone seen this type of behavior as well? I've done a quick demo of this issue here: https://www.youtube.com/watch?v=586_DyN2iFY&ab_channel=KaareBj%C3%B8rnholt-Schou

The issue was not present in Production, but the feature I'm working on is a work in progress, so the components are not a 1:1 match between the two environments.

**Comment by MscrmTools** [comment]
I really don't know why it's behaving this way, knowing that this PCF control does not rely on form events for its rendering

**Comment by Nahassa** [comment]
I got it working a long time ago. I think I ended up uncovering that it had to do with the amount of records in the relationship
