### ISSUE TITLE
i Added the solution to dynamics crm 9.1 but how should use it ?

### ISSUE THREAD

**Issue by Mehran16007** [MscrmTools/PCF-Controls#72]
i Added the solution to dynamics crm 9.1 but how should i use of bottom on my forms ?

**Comment by MscrmTools** [comment]
What control do you want to use?
Anyway, here is the [official documentation](https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/use-custom-controls-data-visualizations) to use custom controls
