### ISSUE TITLE
Backgound and Text Color Source

### ISSUE THREAD

**Issue by ArtKarp** [MscrmTools/PCF-Controls#9]
In your screenshots, you show two columns with color names.  Nothing in your readme doc explains how colors work or what is required. Are these OptionSet fields that have the HEX color set for each option item?  If not, what fields are necessary to specify the color being used?  Can any HEX color be used or are the any limitations?

Great idea for a control!!!
Thanks, 

-Art

![image](https://user-images.githubusercontent.com/25698082/82178479-ee5ce780-9890-11ea-99f6-551bb07ed2ee.png)

**Comment by MscrmTools** [comment]
The value can be the color name or the hexadecimal value

**Comment by ArtKarp** [comment]
Color name and HEX would be text fields.  Can the column be an OptionSet where the HEX color is specified on the chosen option?  

![image](https://user-images.githubusercontent.com/25698082/82986808-5f944d00-9fab-11ea-90ba-6b37993ad13c.png)

**Comment by MscrmTools** [comment]
Actually, yes! If field is an optionset, the color of the optionset value is used

**Comment by ArtKarp** [comment]
Oh, that's great!   
Thanks
