### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by rcjohnson113** [MscrmTools/PCF-Controls#97]
Checkboxes doesn't work anymore 

Error Details: Cannot read properties of undefined (reading 'getAll')

Activity Id: 2eb53783-e31a-4161-a5f5-91d70d2b0777

**Comment by MscrmTools** [comment]
Can you be more specific? Are you talking about NN Checkboxes? If so, what is your configuration? 
It's still working on my side...

**Comment by MscrmTools** [comment]
@rcjohnson113 no answer. I'm closing the issue. Please reopen if you want to give more info
