### ISSUE TITLE
NNCheckboxes Hover/Tooltip field?

### ISSUE THREAD

**Issue by seanmcne** [MscrmTools/PCF-Controls#98]
@MscrmTools  would it be possible to add an optional hover tooltip for checkboxes?  The idea would be to select a field on the entity to show when hovering over the checkbox value (maybe a description field for the given label displayed).

**Comment by MscrmTools** [comment]
Should be possible.
But that would mean that all checkboxes would have the same tooltip, am I correct in my understanding?

**Comment by seanmcne** [comment]
My thought was I am showing 10 categories for check boxes, each of those 10 records (categories) has a 'description' field on them.  For each category checkbox when I hover that specific category would show it's records 'description' value in the tooltip.

**Comment by MscrmTools** [comment]
ah ok! Totally makes sense! I will add this capability

**Comment by MscrmTools** [comment]
Is it what you are after?
![image](https://user-images.githubusercontent.com/10774317/190122973-724f2f4a-e872-410e-a400-aaeeeb3a01a8.png)

Tooltip text comes from attribute "Aide" in the screenshot below
![image](https://user-images.githubusercontent.com/10774317/190123107-0243a5d1-6706-48cf-8dbb-ae0574359af6.png)

**Comment by seanmcne** [comment]
Oh yes that looks about right, is that already a feature and I just didn't figure it out? :)

**Comment by MscrmTools** [comment]
No, I'm currently implementing it and wanted to be sure it was answering your need

**Comment by MscrmTools** [comment]
Available in latest version

**Comment by seanmcne** [comment]
So far the control is working fine for me in the update, but I'm not able to get the tooltips to render/show - I have the attribute selected, any quick tips or ideas to debug it in the browser?  If I look at the network tab I see the requests going to the other entity but it doesn't include the attribute for the tooltip, I'm going to republish again and make sure everything looks updated but just curious if you ran into anything like this.

**Comment by MscrmTools** [comment]
Does the vie defined for the subgrid contains the tooltip column?

**Comment by seanmcne** [comment]
@MscrmTools I have found it work in some cases but not all - I will see if I can figure out when it's not working and if it's an error on my end or not. Thanks again for adding this so quickly!

**Comment by MscrmTools** [comment]
Please check the view definition you are using in the subgrid. It needs the columns for the tooltip. Otherwise, tooltip won't displayed
